"""Cross-process locks preventing two TUFF pipeline runs from executing concurrently.

Real incident, 2026-09-24: a manual `docker exec ... manage.py run_scheduled_tuff` ran at
almost the exact moment celery_worker's own scheduled run_scheduled_tuff_task was already
processing the same 93 ScheduledScope rows -- confirmed, nothing anywhere in this codebase
prevented that. The resulting resource contention caused real data loss: DNS resolution
failures that zeroed out overdue data for several states, and 13 DailyTask rows across 3
PlanRuns that ended up with zero PitchScript, no exception ever logged (a cross-process
SQLite read-visibility race under concurrent writers).

Uses redis-py's own built-in Lock (redis==8.1.0, already a dependency -- confirmed no
django-redis or other locking utility exists anywhere in this codebase) against the same
Redis instance Celery's broker already uses (settings.CELERY_BROKER_URL) -- no new
infrastructure. Two tiers, deliberately separate keys/granularity:

- orchestration_lock(): one global lock, held for an entire run_scheduled_tuff/
  run_all_states_tuff invocation (Step 1 + all of Step 2). Prevents two full orchestration
  passes from ever running at once -- the exact incident above.
- scope_lock(scope_type, scope_value): one lock per (scope_type, scope_value) pair, held for
  a single generate_plan_for_scope() call. Acquired INSIDE generate_plan_for_scope itself
  (not by each caller) so every entrypoint (run_scheduled_tuff, run_all_states_tuff,
  generate_se_plan, activate_tuff, the HTTP scope endpoints) gets this protection
  automatically, with no per-entrypoint code to keep in sync.

Known, deliberately accepted gap: a STATE scope_lock does not block a NODE scope_lock for a
node inside that state (different lock keys) -- fully solving that needs containment-aware
locking (a STATE lock would need to enumerate every NODE name inside it), real complexity
for a narrower risk window than what actually happened. orchestration_lock() alone already
prevents the exact incident (two full passes running at once); this gap is a real, known
residual risk, not silently pretended closed.

Both are non-blocking: if a lock is already held, the caller finds out immediately (False /
LockContendedError) and aborts rather than queuing -- a queued second run would just start
exactly when the first one finishes, doing genuinely redundant work for no benefit, since
every scope this pipeline touches is already covered by whichever run is currently holding
the lock.
"""
from __future__ import annotations

from contextlib import contextmanager
from typing import Iterator

import redis
from django.conf import settings

_redis_client = redis.Redis.from_url(settings.CELERY_BROKER_URL)

# Comfortably longer than any real run has ever taken (today's full 93-scope
# run_scheduled_tuff pass, parallelized, still finished in well under an hour) -- if a lock
# is ever actually held this long, the process holding it has almost certainly crashed
# without releasing it (a container kill mid-run, same as several today), and the TTL is
# what recovers the system rather than a permanently stuck lock.
_ORCHESTRATION_LOCK_TTL_SECONDS = 2 * 60 * 60
_SCOPE_LOCK_TTL_SECONDS = 30 * 60

_ORCHESTRATION_LOCK_KEY = "tuff:orchestration_lock"


class LockContendedError(RuntimeError):
    """Raised when a lock this module manages is already held by another process. Callers
    should treat this as "another run is already in progress," not as an infrastructure
    failure -- abort cleanly, never retry-loop against it (see this module's own docstring
    on why queuing is the wrong response here)."""


@contextmanager
def orchestration_lock() -> Iterator[None]:
    """Acquire the single global orchestration lock, non-blocking. Raises
    LockContendedError immediately if another run_scheduled_tuff/run_all_states_tuff
    invocation already holds it -- callers should catch this at the very top of handle(),
    before Step 1 (Data Normalization) even starts, so a blocked second run does zero live
    Redshift/LLM work rather than getting most of the way through Step 1 first."""
    lock = _redis_client.lock(_ORCHESTRATION_LOCK_KEY, timeout=_ORCHESTRATION_LOCK_TTL_SECONDS)
    if not lock.acquire(blocking=False):
        raise LockContendedError(
            "Another TUFF orchestration run (run_scheduled_tuff or run_all_states_tuff) is "
            "already in progress -- skipping this run rather than running a duplicate pass."
        )
    try:
        yield
    finally:
        lock.release()


@contextmanager
def scope_lock(scope_type: str, scope_value: str) -> Iterator[None]:
    """Acquire a per-(scope_type, scope_value) lock, non-blocking. Raises
    LockContendedError immediately if this exact scope is already being generated by
    another process -- generate_plan_for_scope's own caller (PlanningError propagates
    naturally) sees this as a normal, expected failure mode, same as any other
    PlanningError, not a crash."""
    key = f"tuff:scope_lock:{scope_type}:{scope_value}"
    lock = _redis_client.lock(key, timeout=_SCOPE_LOCK_TTL_SECONDS)
    if not lock.acquire(blocking=False):
        raise LockContendedError(
            f"{scope_type}={scope_value} is already being generated by another process -- "
            f"try again shortly rather than running a duplicate generation for the same scope."
        )
    try:
        yield
    finally:
        lock.release()
