# Generated by Django 6.0.7 on 2026-08-04 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('SE', 'SE'), ('ABM', 'ABM'), ('NODE', 'Node'), ('BLOCK', 'Block'), ('DISTRICT', 'District'), ('STATE', 'State')], max_length=10)),
                ('scope_value', models.CharField(max_length=255)),
                ('plan_date', models.DateField()),
                ('run_timestamp', models.DateTimeField(auto_now_add=True)),
                ('metabase_configured', models.BooleanField(default=False)),
                ('se_count', models.IntegerField(default=0)),
                ('dc_count', models.IntegerField(default=0)),
                ('task_count', models.IntegerField(default=0)),
                ('dynamic_parameters', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-run_timestamp'],
                'indexes': [models.Index(fields=['scope_type', 'scope_value', 'plan_date'], name='planning_pl_scope_t_6d8104_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExceptionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(blank=True, max_length=128, null=True)),
                ('source', models.CharField(max_length=64)),
                ('reason_code', models.CharField(max_length=64)),
                ('detail', models.TextField()),
                ('run_timestamp', models.DateTimeField()),
                ('plan_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='planning.planrun')),
            ],
            options={
                'ordering': ['plan_run', 'reason_code'],
            },
        ),
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('se_id', models.CharField(max_length=64)),
                ('se_name', models.CharField(blank=True, max_length=255, null=True)),
                ('plan_date', models.DateField()),
                ('sr_no', models.IntegerField()),
                ('dc_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dc_id', models.CharField(max_length=32)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('recommended_task_type', models.CharField(max_length=32)),
                ('purpose_of_visit', models.CharField(blank=True, default='', max_length=128)),
                ('reason_of_visit', models.CharField(blank=True, default='', max_length=255)),
                ('last_visit_date', models.DateField(blank=True, null=True)),
                ('days_since_last_visit', models.IntegerField(blank=True, null=True)),
                ('present_outstanding', models.FloatField(blank=True, null=True)),
                ('present_overdue', models.FloatField(blank=True, null=True)),
                ('last_order_date', models.DateField(blank=True, null=True)),
                ('last_order_value', models.FloatField(blank=True, null=True)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('last_payment_join_key_unconfirmed', models.BooleanField(default=True)),
                ('ytd_private_label', models.FloatField(blank=True, null=True)),
                ('dc_club_participation', models.CharField(blank=True, default='', max_length=64)),
                ('objective', models.CharField(blank=True, default='', max_length=32)),
                ('no_new_orders', models.BooleanField(default=False)),
                ('credit_on_hold', models.BooleanField(default=False)),
                ('credit_on_hold_reason', models.CharField(blank=True, max_length=128, null=True)),
                ('estimated_duration', models.IntegerField(default=0)),
                ('priority_multiplier', models.FloatField(default=1.0)),
                ('plan_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='planning.planrun')),
            ],
            options={
                'ordering': ['plan_run', 'se_id', 'sr_no'],
                'indexes': [models.Index(fields=['se_id', 'plan_date'], name='planning_da_se_id_910c1a_idx'), models.Index(fields=['dc_id'], name='planning_da_dc_id_9ab349_idx')],
            },
        ),
    ]
