# Generated by Django 6.0.7 on 2026-08-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='overdue_aging_bucket',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
