# Generated by Django 6.0.7 on 2026-08-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_dailytask_overdue_aging_bucket'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='actual_order_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='actual_payment_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='actual_visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='outcome_status',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partial'), ('MISSED', 'Missed')], default='UNKNOWN', max_length=16),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='reconciled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planrun',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='planrun',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planrun',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planrun',
            name='reviewed_by',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='planrun',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planrun',
            name='status',
            field=models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_REVIEW', max_length=16),
        ),
        migrations.CreateModel(
            name='DCVisitStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('se_id', models.CharField(max_length=64)),
                ('dc_id', models.CharField(max_length=32)),
                ('consecutive_misses', models.IntegerField(default=0)),
                ('last_outcome_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('se_id', 'dc_id'), name='unique_se_dc_streak')],
            },
        ),
        migrations.CreateModel(
            name='ObjectiveCompletionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('se_id', models.CharField(max_length=64)),
                ('objective', models.CharField(max_length=32)),
                ('completion_rate_30d', models.FloatField()),
                ('sample_size', models.IntegerField()),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('se_id', 'objective'), name='unique_se_objective_stats')],
            },
        ),
        migrations.CreateModel(
            name='ScheduledScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('SE', 'SE'), ('ABM', 'ABM'), ('NODE', 'Node'), ('BLOCK', 'Block'), ('DISTRICT', 'District'), ('STATE', 'State')], max_length=10)),
                ('scope_value', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('scope_type', 'scope_value'), name='unique_scheduled_scope')],
            },
        ),
    ]
