# Generated by Django 6.0.7 on 2026-08-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_dailytask_actual_order_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytask',
            name='dc_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
