# Generated by Django 6.0.7 on 2026-08-08 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_alter_dailytask_dc_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PitchScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose_key', models.CharField(max_length=255)),
                ('script_hindi', models.TextField()),
                ('data_sources_used', models.JSONField(blank=True, default=list)),
                ('data_sources_skipped', models.JSONField(blank=True, default=list)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('daily_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pitch', to='planning.dailytask')),
            ],
        ),
    ]
