# Generated by Django 6.0.7 on 2026-08-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_pitchscript'),
    ]

    operations = [
        migrations.AddField(
            model_name='planrun',
            name='skipped_ses',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
