# Generated by Django 6.0.7 on 2026-08-12 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0006_planrun_skipped_ses'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('se_id', models.CharField(max_length=64)),
                ('se_name', models.CharField(blank=True, max_length=255, null=True)),
                ('plan_date', models.DateField()),
                ('plan_type', models.CharField(choices=[('PRIORITY_MAX', 'Priority-Max (Model 1)'), ('DISTANCE_MIN', 'Distance-Min (Model 2)'), ('BALANCED', 'Balanced (Model 3)'), ('SE_OVERRIDE', 'SE Self-Override (Model 4)')], max_length=16)),
                ('origin_lat', models.FloatField(blank=True, null=True)),
                ('origin_lon', models.FloatField(blank=True, null=True)),
                ('origin_basis', models.CharField(choices=[('prev_day_punch_in', "Previous working day's punch-in"), ('waiting_for_today', "No prior punch-in -- deferred to today's real one")], max_length=20)),
                ('total_distance_km', models.FloatField(blank=True, null=True)),
                ('total_travel_minutes', models.FloatField(blank=True, null=True)),
                ('total_visit_minutes', models.FloatField(blank=True, null=True)),
                ('total_minutes', models.FloatField(blank=True, null=True)),
                ('priority_score_captured', models.FloatField(blank=True, null=True)),
                ('feasible', models.BooleanField(default=True)),
                ('infeasibility_reason', models.CharField(blank=True, default='', max_length=255)),
                ('is_default_selected', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('plan_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_plans', to='planning.planrun')),
            ],
            options={
                'ordering': ['plan_run', 'se_id', 'plan_type'],
            },
        ),
        migrations.CreateModel(
            name='RouteDroppedDC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dc_id', models.CharField(max_length=32)),
                ('reason', models.CharField(max_length=255)),
                ('route_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropped_dcs', to='planning.routeplan')),
            ],
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dc_id', models.CharField(max_length=32)),
                ('sequence_no', models.IntegerField()),
                ('purposes', models.CharField(blank=True, default='', max_length=255)),
                ('eta_minutes_from_origin', models.FloatField(blank=True, null=True)),
                ('distance_from_prev_km', models.FloatField(blank=True, null=True)),
                ('travel_time_from_prev_min', models.FloatField(blank=True, null=True)),
                ('visit_duration_min', models.FloatField(default=45.0)),
                ('route_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='planning.routeplan')),
            ],
            options={
                'ordering': ['route_plan', 'sequence_no'],
            },
        ),
        migrations.AddIndex(
            model_name='routeplan',
            index=models.Index(fields=['plan_run', 'se_id'], name='planning_ro_plan_ru_3b37bd_idx'),
        ),
    ]
