# Generated by Django 6.0.7 on 2026-08-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0007_routeplan_routedroppeddc_routestop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeplan',
            name='origin_basis',
            field=models.CharField(choices=[('prev_day_punch_in', "Previous working day's punch-in"), ('today_punch_in', "No prior-day punch-in, but today's own punch-in already happened"), ('waiting_for_today', 'No prior punch-in at all yet -- deferred, no plan generated this run')], max_length=20),
        ),
    ]
