# Generated by Django 6.0.7 on 2026-08-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0008_alter_routeplan_origin_basis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planrun',
            name='scope_type',
            field=models.CharField(choices=[('SE', 'SE'), ('ABM', 'ABM'), ('RBM', 'RBM'), ('NODE', 'Node'), ('BLOCK', 'Block'), ('DISTRICT', 'District'), ('STATE', 'State')], max_length=10),
        ),
        migrations.AlterField(
            model_name='scheduledscope',
            name='scope_type',
            field=models.CharField(choices=[('SE', 'SE'), ('ABM', 'ABM'), ('RBM', 'RBM'), ('NODE', 'Node'), ('BLOCK', 'Block'), ('DISTRICT', 'District'), ('STATE', 'State')], max_length=10),
        ),
    ]
