# Generated by Django 6.0.7 on 2026-08-14 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0009_alter_planrun_scope_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusProductTargetRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_id', models.CharField(max_length=64)),
                ('node_id', models.CharField(max_length=64)),
                ('step_2a', models.JSONField(blank=True, null=True)),
                ('step_2b', models.JSONField(blank=True, null=True)),
                ('step_3', models.JSONField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('plan_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_product_targets', to='planning.planrun')),
            ],
        ),
    ]
