# Generated by Django 6.0.7 on 2026-08-14 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0010_focusproducttargetrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='DCCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_section', models.TextField(blank=True, default='')),
                ('where_dc_stands_section', models.TextField(blank=True, default='')),
                ('private_label_section', models.TextField(blank=True, default='')),
                ('card_hindi', models.TextField()),
                ('data_sources_used', models.JSONField(blank=True, default=list)),
                ('data_sources_skipped', models.JSONField(blank=True, default=list)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('daily_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dc_card', to='planning.dailytask')),
            ],
        ),
    ]
