# Generated by Django 6.0.7 on 2026-08-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0011_dccard'),
    ]

    operations = [
        migrations.AddField(
            model_name='dccard',
            name='recommended_product_brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dccard',
            name='recommended_product_business_segment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dccard',
            name='recommended_product_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dccard',
            name='recommended_product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dccard',
            name='recommended_product_sub_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pitchscript',
            name='recommended_product_brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pitchscript',
            name='recommended_product_business_segment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pitchscript',
            name='recommended_product_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pitchscript',
            name='recommended_product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pitchscript',
            name='recommended_product_sub_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
