# Generated by Django 6.0.7 on 2026-08-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0012_dccard_recommended_product_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dccard',
            name='recommended_product_scope',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='pitchscript',
            name='recommended_product_scope',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
