# Generated by Django 6.0.7 on 2026-08-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0013_dccard_recommended_product_scope_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeplan',
            name='alpha_used',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routeplan',
            name='avg_speed_kmph_used',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
