# Generated by Django 6.0.7 on 2026-08-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0014_routeplan_alpha_used_routeplan_avg_speed_kmph_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='avg_repayment_days',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
