# Generated by Django 6.0.7 on 2026-08-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0015_dailytask_avg_repayment_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dccard',
            name='recommended_product_brand',
        ),
        migrations.RemoveField(
            model_name='dccard',
            name='recommended_product_business_segment',
        ),
        migrations.RemoveField(
            model_name='dccard',
            name='recommended_product_category',
        ),
        migrations.RemoveField(
            model_name='dccard',
            name='recommended_product_name',
        ),
        migrations.RemoveField(
            model_name='dccard',
            name='recommended_product_scope',
        ),
        migrations.RemoveField(
            model_name='dccard',
            name='recommended_product_sub_category',
        ),
        migrations.RemoveField(
            model_name='pitchscript',
            name='recommended_product_brand',
        ),
        migrations.RemoveField(
            model_name='pitchscript',
            name='recommended_product_business_segment',
        ),
        migrations.RemoveField(
            model_name='pitchscript',
            name='recommended_product_category',
        ),
        migrations.RemoveField(
            model_name='pitchscript',
            name='recommended_product_name',
        ),
        migrations.RemoveField(
            model_name='pitchscript',
            name='recommended_product_scope',
        ),
        migrations.RemoveField(
            model_name='pitchscript',
            name='recommended_product_sub_category',
        ),
        migrations.AddField(
            model_name='dccard',
            name='recommended_products',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pitchscript',
            name='recommended_products',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
