# Generated by Django 6.0.7 on 2026-08-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0016_remove_dccard_recommended_product_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='critical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='critical_reasons',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
