# Generated by Django 6.0.7 on 2026-08-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0017_dailytask_critical_dailytask_critical_reasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='club_detail',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
