# Generated by Django 6.0.7 on 2026-08-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0018_dailytask_club_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='dccard',
            name='business_area_detail',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
