# Generated by Django 6.0.7 on 2026-08-24 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0019_dccard_business_area_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='dccard',
            name='club_detail',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dccard',
            name='turnover_detail',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
