# Generated by Django 6.0.7 on 2026-08-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0020_dccard_club_detail_dccard_turnover_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeplan',
            name='plan_type',
            field=models.CharField(choices=[('PRIORITY_MAX', 'Priority-Max (Model 1)'), ('DISTANCE_MIN', 'Distance-Min (Model 2)'), ('BALANCED', 'Balanced (Model 3)'), ('SE_OVERRIDE', 'SE Self-Override (Model 4)'), ('CLUSTER_BASED', 'Cluster-Based Efficiency (Plan B, Route 1)'), ('CLUSTER_SCOREMAX', 'Cluster-Based Score-Max (Plan B, Route 2)'), ('CLUSTER_DISTMIN', 'Cluster-Based Distance-Min (Plan B, Route 3)')], max_length=16),
        ),
    ]
