# Generated by Django 6.0.7 on 2026-09-01 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0021_alter_routeplan_plan_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeatZoneAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('se_id', models.CharField(max_length=64)),
                ('dc_id', models.CharField(max_length=32)),
                ('zone_index', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('num_zones', models.IntegerField()),
                ('anchor_date', models.DateField()),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('se_id', 'dc_id')},
            },
        ),
    ]
