# Generated by Django 6.0.7 on 2026-09-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0022_beatzoneassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beatzoneassignment',
            name='se_id',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
