# Generated by Django 6.0.7 on 2026-09-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0023_alter_beatzoneassignment_se_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='finance_status',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
