# Generated by Django 6.0.7 on 2026-09-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0024_dailytask_finance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='bo_scores',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
