# Generated by Django 6.0.7 on 2026-09-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0025_dailytask_bo_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='bo_composite_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='bo_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
