# Generated by Django 6.0.7 on 2026-09-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0026_dailytask_bo_composite_score_dailytask_bo_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='promise_status',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='promise_to_pay_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='promise_to_pay_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
