# Generated by Django 6.0.7 on 2026-09-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0027_dailytask_promise_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeplan',
            name='origin_basis',
            field=models.CharField(choices=[('prev_day_punch_in', "Previous working day's punch-in (legacy, pre-2026-09-04)"), ('prev_30d_punch_in', "Majority of last 30 days' punch-ins (500m cluster)"), ('today_punch_in', "No prior-day punch-in, but today's own punch-in already happened"), ('waiting_for_today', 'No prior punch-in at all yet -- deferred, no plan generated this run')], max_length=20),
        ),
    ]
