# Generated by Django 6.0.7 on 2026-09-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0028_alter_routeplan_origin_basis'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='dc_health_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='health_focus_purposes',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='health_focus_track',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='health_gap',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='health_sub_scores',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='negative_gm_flag',
            field=models.BooleanField(default=False),
        ),
    ]
