# Generated by Django 6.0.7 on 2026-09-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0029_dailytask_dc_health_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dccard',
            name='health_score_detail',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dccard',
            name='health_score_section',
            field=models.TextField(blank=True, default=''),
        ),
    ]
