# Generated by Django 6.0.7 on 2026-09-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0030_dccard_health_score_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='available_credit_limit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='credit_active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='credit_limit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
