# Generated by Django 6.0.7 on 2026-09-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0032_pipelinesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramDCSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules', models.JSONField(blank=True, default=dict)),
                ('manual_includes', models.JSONField(blank=True, default=list)),
                ('manual_excludes', models.JSONField(blank=True, default=list)),
                ('rank_csv_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('rank_csv_uploaded_by', models.CharField(blank=True, default='', max_length=200)),
                ('rank_csv_row_count', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
    ]
