# Generated by Django 6.0.7 on 2026-09-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0033_programdcselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='programdcselection',
            name='upload_mode',
            field=models.CharField(choices=[('uploaded_plus_filter', 'Uploaded list + optional filter'), ('uploaded_only', 'Uploaded list only')], default='uploaded_plus_filter', max_length=30),
        ),
    ]
