# Generated by Django 6.0.7 on 2026-09-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0034_programdcselection_upload_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeplan',
            name='distance_source',
            field=models.CharField(choices=[('haversine_x1.4', 'Haversine x 1.4 estimate'), ('google_maps', 'Google Maps (real road distance/time)')], default='haversine_x1.4', max_length=20),
        ),
        migrations.AddField(
            model_name='routeplan',
            name='google_exceeds_cap',
            field=models.BooleanField(default=False),
        ),
    ]
