# Generated by Django 6.0.7 on 2026-09-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0035_routeplan_distance_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutingScopeOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('NODE', 'Node'), ('STATE', 'State')], max_length=10)),
                ('scope_value', models.CharField(max_length=255)),
                ('r1_2_max_travel_minutes', models.FloatField(blank=True, null=True)),
                ('plan_a_max_round_trip_distance_km', models.FloatField(blank=True, null=True)),
                ('plan_b_max_daily_distance_km', models.FloatField(blank=True, null=True)),
                ('plan_b_max_daily_travel_minutes', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('scope_type', 'scope_value'), name='unique_routing_scope_override')],
            },
        ),
    ]
