# Generated by Django 6.0.7 on 2026-09-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0036_routingscopeoverride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routingscopeoverride',
            name='scope_type',
            field=models.CharField(choices=[('NODE', 'Node'), ('DISTRICT', 'District'), ('STATE', 'State')], max_length=10),
        ),
    ]
