# Generated by Django 6.0.7 on 2026-09-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0037_alter_routingscopeoverride_scope_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeplan',
            name='llm_reasoning',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='routeplan',
            name='plan_type',
            field=models.CharField(choices=[('PRIORITY_MAX', 'Priority-Max (Model 1)'), ('DISTANCE_MIN', 'Distance-Min (Model 2)'), ('BALANCED', 'Balanced (Model 3)'), ('SE_OVERRIDE', 'SE Self-Override (Model 4)'), ('CLUSTER_BASED', 'Cluster-Based Efficiency (Plan B, Route 1)'), ('CLUSTER_SCOREMAX', 'Cluster-Based Score-Max (Plan B, Route 2)'), ('CLUSTER_DISTMIN', 'Cluster-Based Distance-Min (Plan B, Route 3)'), ('LLM_REASONED', 'AI-Reasoned (Plan C, Anthropic Claude)')], max_length=16),
        ),
    ]
