# Generated by Django 6.0.7 on 2026-09-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0038_routeplan_llm_reasoning_alter_routeplan_plan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchscript',
            name='ai_sales_forecast',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
