# Generated by Django 6.0.7 on 2026-09-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0040_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeplan',
            name='expected_value_captured',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routeplan',
            name='expected_value_dc_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='routeplan',
            name='value_per_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routeplan',
            name='plan_type',
            field=models.CharField(choices=[('PRIORITY_MAX', 'Priority-Max (Model 1)'), ('DISTANCE_MIN', 'Distance-Min (Model 2)'), ('BALANCED', 'Balanced (Model 3)'), ('SE_OVERRIDE', 'SE Self-Override (Model 4)'), ('CLUSTER_BASED', 'Cluster-Based Efficiency (Plan B, Route 1)'), ('CLUSTER_SCOREMAX', 'Cluster-Based Score-Max (Plan B, Route 2)'), ('CLUSTER_DISTMIN', 'Cluster-Based Distance-Min (Plan B, Route 3)'), ('LLM_REASONED', "AI-Reasoned (Plan C, Route 1 - admin's configured style)"), ('LLM_REASONED_VALUE_MAX', 'AI-Reasoned (Plan C, Route 2 - Value-Max)'), ('LLM_REASONED_DISTMIN', 'AI-Reasoned (Plan C, Route 3 - Distance-Min)')], max_length=24),
        ),
    ]
