# Generated by Django 6.0.7 on 2026-09-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0041_routeplan_expected_value_captured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeplan',
            name='manually_edited',
            field=models.BooleanField(default=False),
        ),
    ]
