# Generated by Django 6.0.7 on 2026-09-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0042_routeplan_manually_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='dccard',
            name='active_schemes_detail',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dccard',
            name='active_schemes_section',
            field=models.TextField(blank=True, default=''),
        ),
    ]
