"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Loads REDSHIFT_HOST/PORT/USER/PASSWORD/DB_* (and METABASE_URL/METABASE_API_KEY, if used
# instead) from .env -- gitignored, never commit real credentials. See
# se_daily_plan_agent.RedshiftDirectClient / get_client() for how these are consumed.
load_dotenv(BASE_DIR / ".env")

# Slack incoming-webhook URL for planning.notify.send_alert() -- optional, .env-sourced.
# Alerting is a no-op (log-only) when unset, see planning/notify.py.
ALERT_WEBHOOK_URL = os.environ.get("ALERT_WEBHOOK_URL", "")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Sourced from .env (gitignored) -- a real, randomly generated key lives there now,
# not the django-admin-startproject placeholder that used to be hardcoded here. The
# fallback below only fires if .env is missing entirely, and is deliberately marked
# "insecure" (same convention Django itself uses) so it's obvious in any error output.
SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-fallback-set-SECRET_KEY-in-.env")

# SECURITY WARNING: don't run with debug turned on in production!
# .env-driven so a future real deployment can set DEBUG=False without a code change --
# defaults to True here since this is still a local-only setup (no WSGI/gunicorn, see
# the infra audit) and flipping the default would silently break `runserver` today.
DEBUG = os.environ.get("DEBUG", "True") == "True"

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'testserver']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'planning',
]

# se_daily_plan_agent.py lives at the project root -- imported as a library by
# planning/services.py rather than duplicated. See AGENT_OPERATING_PROMPTS.md.
SE_DAILY_PLAN_AGENT_PATH = BASE_DIR

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        # Django's sqlite3 default connect timeout is 5s. The frontend fires
        # routing_plan=B and routing_plan=C as two concurrent requests for the same SE,
        # each independently reading DC/order data then writing a full PlanRun.
        # Confirmed live 2026-09-15, in 3 stages:
        #  1. Raising 'timeout' alone does nothing -- SQLite's default DEFERRED
        #     transaction mode lets two connections each acquire a read lock, then BOTH
        #     try to upgrade to a write lock at once. That's SQLITE_BUSY (rollback-
        #     journal mode) or SQLITE_BUSY_SNAPSHOT (WAL mode) -- both return
        #     "database is locked" INSTANTLY, not after a wait, because no amount of
        #     retrying resolves a two-way upgrade conflict / stale read snapshot.
        #  2. journal_mode=WAL alone (set once on the db file, reasserted here since
        #     it's a per-connection PRAGMA) doesn't fix it either, for the same reason --
        #     WAL still hits SQLITE_BUSY_SNAPSHOT on a stale-snapshot write attempt.
        #  3. transaction_mode='IMMEDIATE' is what actually fixes it -- makes every
        #     Django atomic() block issue BEGIN IMMEDIATE, acquiring the write lock
        #     upfront (before any reads) instead of deferring, so a second concurrent
        #     request cleanly queues behind the first (honoring 'timeout') instead of
        #     deadlocking. Django >=5.1 native OPTIONS key. WAL is kept too -- it's still
        #     the right on-disk mode for concurrent readers once writers stop deadlocking.
        #  4. 'timeout' raised 30 -> 300 (2026-09-16): queueing only helps if the wait is
        #     long enough. generate_plan_for_scope is ONE atomic block around the whole
        #     generation -- Redshift pulls, routing, LLM calls, pitching -- so a Plan C
        #     run holds the write lock for 2+ minutes (confirmed live: 2m13s), and a
        #     request queued behind it (an SE switching Today -> Tomorrow while today's
        #     plan was still generating) gave up at 30s with "database is locked"
        #     every time. 300s covers two Plan C generations back to back. The real
        #     fix is narrowing that atomic block to the write phase; until then, wait.
        'OPTIONS': {
            'timeout': 300,
            'init_command': 'PRAGMA journal_mode=WAL;',
            'transaction_mode': 'IMMEDIATE',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Persist TUFF's own logging (se_daily_plan_agent's "se_daily_plan_agent" logger, plus
# planning.*) to a rotating file, on top of the existing stdout output -- previously
# logging.basicConfig() in se_daily_plan_agent.py only wrote to stdout, so an unattended
# (cron) run's logs were lost the moment the terminal closed.
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '%(asctime)s %(levelname)s %(name)s: %(message)s',
        },
    },
    'handlers': {
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'tuff.log',
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'standard',
        },
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
}
